### ISSUE TITLE
[Feature request]: New Trophy Event

### ISSUE THREAD

**Issue by codyhackw** [FunkeyFlo/ps5-mqtt#156]
### Is your feature request related to a problem? Please describe

There's no way of triggering an automation if you get a trophy while playing a game.

### Describe the solution you'd like

It would be really cool to get a sensor in HA that turns on or ties into user activity to track when you get a new trophy in a game.

### Describe alternatives you've considered

Unsure if a sensor is the right way of going about it, but pretty sure the only way to get the info would be an API call similar to how this works today for state/activity, etc.

### Additional context

My guess as to how this would look is:
Build out the list of a user's trophies using - https://psn-api.achievements.app/api-docs/user-trophies
Check to see if the # of trophies is higher than the existing list or has increased since the last check, if true, then trigger a sensor in HA and then reset the existing # being tracked. If false, don't worry about it.

**Comment by FunkeyFlo** [comment]
@codyhackw thanks for your feature request! This seems like a fun feature to add. I thought about it myself as well.

However, due to #155 I am reluctant to add any features that require additional polling of the PSN API's. Since account activity and trophies cannot be acquired within the same API call this would double the amount of requests the addon will make.
