### ISSUE TITLE
Discovered PS5 becomes unavailable when turned off

### ISSUE THREAD

**Issue by nioakeim** [FunkeyFlo/ps5-mqtt#158]
### Description of the issue

Discovered PS5 becomes unavailable when turned off

Expected Behaviour:
When a device is discovered and entities are created, i would expect that the entity would have a status to off instead of unavailable. 

### Addon version

1.3.1

### Platform

Home Assistant 2022.12.7
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

**Comment by FunkeyFlo** [comment]
I implemented the behaviour to be similar to that off the existing HA Xbox integration, to be consistent.

Since there is no way to determine if the device still exists in the network, a.k.a. your home, I would disagree and say that `unavailable` is the correct status when the device is powered off.

If you think the behaviour should be different I suggest creating a custom `media_player` entity as shown [here](https://discord.com/channels/1001939827358453792/1021936995402006568).

**Comment by nioakeim** [comment]
You are right. I am closing my issue report. Thank you for your time 😀
