### ISSUE TITLE
Too Many Requests - when obtaining a new token

### ISSUE THREAD

**Issue by jlipsit** [FunkeyFlo/ps5-mqtt#385]
### Description of the issue

Thanks for making this add on!  I really appreciate you sharing it with us all. 

After my NPSSO expired I get this error when attempting to get a new token.

![Sony - Too Many Requests](https://github.com/FunkeyFlo/ps5-mqtt/assets/155367039/c07fd246-69ad-4575-bc33-3a82234ac2c6)

```
“HTTP Status 429 – Too Many Requests”
Type Status Report
Description The user has sent too many requests in a given amount of time ("rate limiting").
```
My “guess” is that the Add-On is hitting the site repeatedly when the token has expired and now the user is not able to obtain a token because the site has blocked access.  Have you seen this before and is there a way to detect that the token has expired and to notify the user?

### Addon version

1.3.3

### Platform

Core
2024.2.5
Supervisor
2024.02.1
Operating System
12.0
Frontend
20240207.1

### Logs of the issue (if applicable)

None

**Comment by FunkeyFlo** [comment]
How do you know it expired?

The add-on can't make requests on your behalf when the token is no longer valid. That means it cannot be the cause of exceeding the limit, because it's not "you" making the requests.

So I suspect your token isn't expired.

However, if the add-on exceeds the limit with a valid token try increasing the gap between requests using [this setting](https://github.com/FunkeyFlo/ps5-mqtt/blob/main/add-ons/ps5-mqtt/DOCS.md#account_check_interval).

**Comment by jlipsit** [comment]
![PS5-Error](https://github.com/FunkeyFlo/ps5-mqtt/assets/155367039/61cf6a35-f2c4-454a-a4de-db5c26e87b09)

Hi, I set this up months ago and it worked up until this point, so I assumed the NPSSO expired. When I attempt to get a new one I still get that "Too many requests" error.  I just have 1 PS5 and do not use it much. No sure why I am continuing to see the "Too Many Attempts" error on the Sony Site. Any Ideals?  Thanks.

**Comment by jlipsit** [comment]
I just figured this out.  My account was not fully logged in with 2- factor authentication. Once I did this and trusted the browser - I got the updated key.  Sorry to bother you with this. Have a great weekend!
